#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const frontendDir = path.resolve(__dirname, '..');
const repoRoot = path.resolve(frontendDir, '..');
const outputPath = path.join(frontendDir, 'js', 'env.js');
const publicKeys = [
  'INSFORGE_API_URL',
  'INSFORGE_ANON_KEY',
  'INSFORGE_SDK_URL',
];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  return dotenv.parse(fs.readFileSync(filePath));
}

const sources = [
  parseEnvFile(path.join(repoRoot, '.env.local')),
  parseEnvFile(path.join(repoRoot, '.env')),
  process.env,
];

const publicEnv = {};
sources.forEach((source) => {
  publicKeys.forEach((key) => {
    if (typeof source[key] === 'string' && source[key].trim()) {
      publicEnv[key] = source[key].trim();
    }
  });
});

if (!publicEnv.INSFORGE_SDK_URL) {
  publicEnv.INSFORGE_SDK_URL = 'https://esm.sh/@insforge/sdk@1.4.3';
}

const body = `// Generated by frontend/scripts/generate-env.js. Do not edit by hand.
(function () {
    'use strict';

    window.AppEnv = ${JSON.stringify(publicEnv, null, 4)};
})();
`;

fs.writeFileSync(outputPath, body);
console.log(`Wrote ${path.relative(frontendDir, outputPath)} with ${Object.keys(publicEnv).length} public value(s).`);
